### ISSUE TITLE
dns_suffix parameter is missing in vcd_vapp_network.py

### ISSUE THREAD

**Issue by carmine73** [carmineesposito73/ansible-module-vcloud-director#5]
vapp networks can have a dns_suffix, this parameter is missing in vcd_vapp_network.py and dns_suffix cannot be set

**Comment by IAmAnthem** [comment]
FYI I saw your work on vcd_vapp_network.py never made it to the main project, and I needed some of the additions you did!

The one thing that seems to not be working is dns_suffix.
It doesn't throw any errors I can see in ansible, but I haven't dug into the logging to validate any further.

Any chance your changes are going to get committed up to the VMware modules?

**Comment by carmine73** [comment]
Hi @IAmAnthem, my PR was not approved (probably I wasn't able to make a complete PR).
I'm not working much on this module (I'm not in the team that works on the official module), I would like to test and fix the dns_suffix issue, but actually now I do not have much time.
It seems to me the team is not interested in my work and they do not want to integrate it.
Actually now I use terraform https://www.terraform.io/docs/providers/vcd/index.html

**Comment by IAmAnthem** [comment]
Thanks for the info, do you find terraform to be a more complete solution?  I am still in a prototype phase and ansible seems to work for much of our environment, aside from these little spots where it doesn't!   Haven't done much but glance at terraform.

**Comment by carmine73** [comment]
@IAmAnthem I think terraform is a better provisioning solution than ansible for vCloud (I haven't used these tools for others cloud platforms). As far as I know there is official support on terraform vcloud provider by vmware, while ansible vcloud module is community supported.
I can suggest this article https://blog.gruntwork.io/why-we-use-terraform-and-not-chef-puppet-ansible-saltstack-or-cloudformation-7989dad2865c to have a better description of provisioning/configuration management tools
